### ISSUE TITLE
startup crash, incompatibility with RFtools

### ISSUE THREAD

**Issue by stclaus4** [Mowmaster/ENDPOINT#2]
http://pastebin.com/fTaGKwkU
i believe we have a problem here with the recipes shape for the machine frame. this crash is from start up.
upon removal of Endpoint the problem was solved it seems.

**Comment by Mowmaster** [comment]
Sorry about the delay, it should be fixed in the latest build, The server NEoA is for also had this issue which has been resolved(Bad spelling error on my part)
